apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: consul-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-consul-server-0
spec:
  storageClassName: "consul-local-storage"
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/srv/consul/data"
  volumeMode: Filesystem