- name: Deploy istio changes.
  hosts: istio
  remote_user: sysadmin

  tasks:

    - name: Create emojivote directory.
      become: no
      ansible.builtin.file:
        path: emojivote
        state: directory
        mode: '0755'

    - name: Copy ingress for emojivote.
      ansible.builtin.copy:
        src: "files/istio/ingress.yaml"
        dest: "emojivote/ingress.yaml"

    - name: Apply ingress for emojivote.
      shell: kubectl apply -f emojivote/ingress.yaml
